### ISSUE TITLE
Closing Sketch Miner tab and trying to open again generates Webview is disposed error

### ISSUE THREAD

**Issue by jwallander** [s-v-o/vscode-bpmn-sketch-miner#1]
Extension version v1.0.3

Version: 1.89.1 (user setup)
Commit: dc96b837cf6bb4af9cd736aa3af08cf8279f7685
Date: 2024-05-07T05:13:33.891Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Windows_NT x64 10.0.19045

**Comment by s-v-o** [comment]
Thank you, I was able to replicate the issue and will look into it.

What works is to leave when you let the tab been open and repeat the "Show BPMN" command to refresh the tab.
But after closing the tab, with the current version, I see no other possibility than to restart VSCode.

**Comment by s-v-o** [comment]
Should be fixed in 1.0.4
