### ISSUE TITLE
Using Show BPMN command generates command bpmn-sketch-miner.show not found error

### ISSUE THREAD

**Issue by jwallander** [s-v-o/vscode-bpmn-sketch-miner#3]
Extension version 1.0.4.

Tried switching back to 1.0.3 and then it works again but it stops working again when updating to 1.0.4.

Version: 1.89.1 (user setup)
Commit: dc96b837cf6bb4af9cd736aa3af08cf8279f7685
Date: 2024-05-07T05:13:33.891Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Windows_NT x64 10.0.19045

**Comment by s-v-o** [comment]
I'm sorry, it seems there was some error in my package / publish process.
Hope it will work now as expected.

**Comment by jwallander** [comment]
1.0.5 works as intended. Thanks!

The two reasons I use your extension is that I want to control when the diagram is updated and also to have easier version control.
